VALID_AREAS = [
    # Central Coimbatore
    "Gandhipuram",
    "RS Puram",
    "Ukkadam",
    "Town Hall",
    "Peelamedu",
    "Kalapatti",
    "Saravanampatti",
    "Thudiyalur",
     "perur",
     "ramanathapuram",
     "Singanallur",
     "MGR Street, Coimbatore",
     "Madhampatti",
     "kaundampalayam",
     "Saibaba colony",
     "Ganapathy",
     "Race course",
     "vadavalli",
     "Thondamuthur",
     "Vadakovai",
     "Chitra",
     "Podanur",
     "KovaiPudur",
     "kuniamuthur",
     "madukkarai",
     "Arasur",
     "Karumathampatti",
    "Cheran nagar",
    "Vilankurichi",
    "Neelambur",
    "Kovilpalayam",
    "Keeranatham",
    "NGP College",
    "PSG College",
    "KMCH",
    "Codissia",

    # North Coimbatore
    "Annur",
    "Karamadai",
    "Mettupalayam Road",
    "Sulur",
    "Irugur",
    "Ondipudur",
]
